### ISSUE TITLE
加载模型推理问题

### ISSUE THREAD

**Issue by xczhusuda** [JusperLee/TDANet#27]
您好，李博
我在使用您的模型推理的时候遇到了问题，可以帮忙看看吗？
这是您的推理代码：
import os
import torch
import look2hear.models
import torchaudio
os.environ['CUDA_VISIBLE_DEVICES'] = "0"
mix, sr = torchaudio.load("audio_mix.wav")
transform = torchaudio.transforms.Resample(sr, 16_000)
mix = transform(mix)
mix = mix.view(1, 1, -1)
model = look2hear.models.BaseModel.from_pretrain("TDANetBest-2ms-LRS2/pytorch_model.bin").cuda()
est_sources = model(mix.cuda())
torchaudio.save("audio1sep.wav", est_sources[:, 0, :].detach().cpu(), 16_000)
torchaudio.save("audio2sep.wav", est_sources[:, 1, :].detach().cpu(), 16_000)
这是报错问题：
python inference.py
Traceback (most recent call last):
  File "**/speech_separation/inference.py", line 13, in <module>
    model = look2hear.models.BaseModel.from_pretrain("TDANetBest-2ms-LRS2/pytorch_model.bin").cuda()
  File "**/speech_separation/look2hear/models/base_model.py", line 137, in from_pretrain
    conf = torch.load(
  File "/opt/conda/envs/py310torch201/lib/python3.10/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/envs/py310torch201/lib/python3.10/site-packages/torch/serialization.py", line 1262, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by JusperLee** [comment]
model = look2hear.models.BaseModel.from_pretrain("JusperLee/TDANetBest-2ms-LRS2").cuda()
