### ISSUE TITLE
Training TDAnet with Librimix and LSR2 dataset

### ISSUE THREAD

**Issue by temismink** [JusperLee/TDANet#30]
Hello, I've tried loading in data with this command: 
`python DataPreProcess/process_librimix.py --in_dir=xxxx --out_dir=DataPreProcess/Libri2Mix`
for two datasets: LibriMix and LRS2. However, none of the datasets have the structure that's expected by the code.

I used LibriSpeech here which has train-clean-100 instead of train-100 which I changed, but I see no folder called mix_clean in it.

`Traceback (most recent call last):
  File "DataPreProcess/process_librimix.py", line 57, in <module>
    preprocess_librimix_audio(args)
  File "DataPreProcess/process_librimix.py", line 39, in preprocess_librimix_audio
    preprocess_one_dir(
  File "DataPreProcess/process_librimix.py", line 12, in preprocess_one_dir
    wav_list = os.listdir(in_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/LibriMix/storage_dir/LibriSpeech/train-clean-100/mix_clean'`

I used LRS2 here and got the same error when I tried all the possible directories of LRS2. There is no folder called mix_clean in LRS2. Please provide any help because I followed the instructions step by step and issues still arise.

Thanls

**Comment by temismink** [comment]
Nevermind realized the structure from the code.
