### ISSUE TITLE
Dimention mismatch

### ISSUE THREAD

**Issue by Suchalongtime** [JusperLee/TDANet#5]
学长您好，我参考您的Dual-Path-RNN-Pytorch代码来复现这个项目时遇到了以下错误：
23-05-11 15:42:51 [F:\Audio_Separation\Code\TDANet\train_TDANet.py:66 - INFO ] Building the model of TDANet
23-05-11 15:42:51 [F:\Audio_Separation\Code\TDANet\train_TDANet.py:69 - INFO ] Building the optimizer of TDANet
23-05-11 15:42:51 [F:\Audio_Separation\Code\TDANet\train_TDANet.py:72 - INFO ] Building the dataloader of TDANet
23-05-11 15:42:52 [F:\Audio_Separation\Code\TDANet\train_TDANet.py:75 - INFO ] Train Datasets Length: 20, Val Datasets Length: 18
23-05-11 15:42:52 [F:\Audio_Separation\Code\TDANet\train_TDANet.py:85 - INFO ] Building the Trainer of TDANet
23-05-11 15:42:52 [F:\Audio_Separation\Code\TDANet\trainer\trainer_TDANet.py:35 - INFO ] Load Nvida GPU .....
23-05-11 15:42:52 [F:\Audio_Separation\Code\TDANet\trainer\trainer_TDANet.py:40 - INFO ] Loading TDANet parameters: 2.642 Mb
23-05-11 15:42:52 [F:\Audio_Separation\Code\TDANet\trainer\trainer_TDANet.py:68 - INFO ] Gradient clipping by 5, default L2
23-05-11 15:42:52 [F:\Audio_Separation\Code\TDANet\trainer\trainer_TDANet.py:115 - INFO ] Start Validation from epoch: 0, iter: 0
Traceback (most recent call last):
  File "F:\Audio_Separation\Code\TDANet\train_TDANet.py", line 91, in <module>
    train()
  File "F:\Audio_Separation\Code\TDANet\train_TDANet.py", line 87, in train
    trainer.run()
  File "F:\Audio_Separation\Code\TDANet\trainer\trainer_TDANet.py", line 155, in run
    v_loss = self.validation(self.cur_epoch)
  File "F:\Audio_Separation\Code\TDANet\trainer\trainer_TDANet.py", line 135, in validation
    l = Loss(out, ref)
  File "F:\Audio_Separation\Code\TDANet\model\loss.py", line 44, in Loss
    [sisnr_loss(p) for p in permutations(range(num_spks))])
  File "F:\Audio_Separation\Code\TDANet\model\loss.py", line 44, in <listcomp>
    [sisnr_loss(p) for p in permutations(range(num_spks))])
  File "F:\Audio_Separation\Code\TDANet\model\loss.py", line 37, in sisnr_loss
    [sisnr(ests[s], refs[t])
  File "F:\Audio_Separation\Code\TDANet\model\loss.py", line 37, in <listcomp>
    [sisnr(ests[s], refs[t])
  File "F:\Audio_Separation\Code\TDANet\model\loss.py", line 18, in sisnr
    raise RuntimeError(
RuntimeError: Dimention mismatch when calculate si-snr, torch.Size([2, 32000]) vs torch.Size([1, 32000])

进程已结束,退出代码1

下面是我的代码，请问我需要怎么进行修改呢？
![image](https://github.com/JusperLee/TDANet/assets/65219883/f9a0c4eb-b0dd-4384-9280-0199f2b3bee8)

**Comment by JusperLee** [comment]
我觉得应该是我输出的[batch, 2, T]，你应该是对batch的进行循环了。你可以考虑将我这个模型嵌入到Asteroid中去训练，应该更方便一些。解决办法就是你在\loss.py line 37行前输出一下维度，看看是否能匹配上。

推荐使用Asteroid来训练和验证，会更容易些。

**Comment by Suchalongtime** [comment]
> 

好的，我用Asteroid尝试一下，谢谢学长啦！
